### ISSUE TITLE
Menu: "New Trial" should be called "Configure Project Settings"

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#14]
This is mislabeled - clicking on this brings up a pane that allows the user to define settings for the whole project. 

(Just to clarify: a "Trial" is literally a single user-defined portion of one video; so each spreadsheet is likely to contain potentially hundreds of "trials" - one row of data for each.)

**Comment by eringt** [comment]
That matches my intuitive definition of a trial but the existing code seemed to imply they weren't individual trials but subsections of a trial. Will change the label to "Create new project" as configure project settings sounds like you can reconfigure a project (which you currently can't).

**Comment by alexisgarland** [comment]
Consolidated with other renaming issues
