### ISSUE TITLE
Menu: "Load Trial" should be called "Load Existing Project Spreadsheet"

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#15]
This just makes the function of this clearer - they aren't loading a Trial, they are loading a spreadsheet they've already created with this program (which happens to have project settings embedded in it).

**Comment by eringt** [comment]
Do you consider the spreadsheet part of the label important? As to me, the spreadsheet is a project with data embedded in it. So it would be "Load existing project" as the spreadsheet is the save file for a project.

**Comment by alexisgarland** [comment]
Consolidated with other renaming issues
