### ISSUE TITLE
Fix Versioning

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#17]
The last version release and the last draft are both labeled 0.2 within the program itself, but the last release is labeled 2.0 in Github. Maybe rename the whole program itself to "BehaviourCoder" instead of RoosterCoder" and make this 1.0 with the generalization improvements included.

**Comment by johndeverall** [comment]
We will use github commit hash and date for versioning and display the version info under help, version in the menu bar.

**Comment by varghesemathew92** [comment]
Closed in version 2017-10-15_020113_c62cea4
