### ISSUE TITLE
Relabel lots of things !!!

### ISSUE THREAD

**Issue by alexisgarland** [johndeverall/BehaviourCoder#25]
Relabel: 

In the Main menu - 
- [x] "new trial" to "Set Up New Experiment"
- [x] "load trial" to "Load Experiment Settings"
- [x] "new session" to "Load New Video for Analysis"
- [x] "restart session" to "Restart Analysis"

When you start a new trial/exp -
- [x] "timed behaviors" to "Time a Behavior"
- [x] "instant behaviors" to "Count a Behavior"
- [x] "Details" to "Experiment Trial Details: Subject, Identifying Information, Family Group, Context, etc."
- [x] after you do your settings it says "open" instead of "save" when you go to save your xls file

**Comment by varghesemathew92** [comment]
Closed in version 2017-10-15_020113_c62cea4
