### ISSUE TITLE
VLC video libraries are corrupted on extraction from jar

### ISSUE THREAD

**Issue by johndeverall** [johndeverall/BehaviourCoder#58]
**Replication steps**

1. Download the version of behaviour coder  from [this page here](https://github.com/johndeverall/BehaviourCoder/releases/tag/v2017-10-12_195126_25a2ebc).

2. Run the behaviour coder with the executable jar. You will see that the VLC libraries are extracted from the jar and included in the lib folder in the same location as the executable jar. The behavour coder will not start.

3. Download the lib.zip file from [this page]( https://github.com/johndeverall/BehaviourCoder/releases/tag/v2017-10-12_195126_25a2ebc) and replace the lib folder created by the executable jar with its contents. 

4. Run the Behaviour Coder again. It will now start. The previous failure seems to be caused by the VLC lib files being corrupted on extraction from the executable jar.

**Comment by varghesemathew92** [comment]
Closed in version 2017-10-15_020113_c62cea4
