### ISSUE TITLE
Application does not run

### ISSUE THREAD

**Issue by JudyCham** [johndeverall/BehaviourCoder#72]
**Replication Steps**

1. Download the application from https://github.com/johndeverall/BehaviourCoder/releases/tag/v2017-10-15_020113_c62cea4

2. Find the application in the download location

3. Double click on the application to run it

4. The following log information results (attached) 

[behaviour-coder-2017-12-03_23-40-41.369.log](https://github.com/johndeverall/BehaviourCoder/files/1524668/behaviour-coder-2017-12-03_23-40-41.369.log)

**Comment by johndeverall** [comment]
@JudyCham thanks for the bug report and great replication steps. From the logs I think what is happening is that you have a 32 bit JVM installed, and there's a bug in the app with loading the 32 bit libraries.

**Comment by johndeverall** [comment]
@JudyCham I've released a new version of the software [here](https://github.com/johndeverall/BehaviourCoder/releases/tag/v2018-02-17_005226_9999c3c). Do you mind just confirming that it works on your machine now? :)

**Comment by JudyCham** [comment]
@johndeverall Yes the application will run on my machine now, thank you.
