### ISSUE TITLE
Need to be able to lay out location buttons in more complex layouts

### ISSUE THREAD

**Issue by johndeverall** [johndeverall/BehaviourCoder#8]
There are a couple of options I've thought of here:

**1) Buttons could be fixed on a grid using standard swing components.**

Coordinate entry would work ok for generating something like this, which is a format that was useful for the Indian Myna study (Birds moving quickly between areas of a cage might indicate stress for example).

![myna cage](https://cloud.githubusercontent.com/assets/3393900/12948506/74b378a4-d067-11e5-855f-66016f0ab06d.png)

**2) Buttons could be drawn in SVG.**

[This library](http://www.jfree.org/jfreesvg/) looks as if it could be useful for generating SVG.

I have not investigated whether is has enough capability to do what we require though. Other libraries available are [SVG Salamander](https://svgsalamander.java.net/users.html) and [Batik](https://xmlgraphics.apache.org/batik/) but these may require SVG images in advance or at least did last time I used them (which was a long time ago - back in 2009).

SVG would allow more complex layouts to be created. For example, lets say a researcher wanted to record the behaviour of multiple people playing [hopscotch](https://www.youtube.com/watch?v=fZzswQaICfMp).

The following layout, or even more complex layouts (with round areas etc) would be easily possible with SVG although it may take slightly more work to implement.

![hopscotch](https://cloud.githubusercontent.com/assets/3393900/12948586/cfd6af26-d067-11e5-9d0f-07467aeca2d5.png)

**Comment by johndeverall** [comment]
@alexisgarland can you please clarify this requirement

**Comment by alexisgarland** [comment]
If there's a choice, it would be best to have a fairly flexible layout - these buttons are serving as kind of a "map" of areas on the video - so the more flexible it is for the user to place them, the more the interface is going to actually reflect what is going on in the video.

**Comment by johndeverall** [comment]
Can you please comment specifically upon the methods above that are proposed? Which method sounds better to you? With the first method, I could supply a grid of cells, of dimension x and y, where each cell was either a button, or an object (with or without a label). Objects aren't clickable, so they'd just sit there and look pretty.

**Comment by varghesemathew92** [comment]
Closed in version 2017-10-15_020113_c62cea4
