### ISSUE TITLE
Remove static 'mirror' and provide function for user to add static non-button objects in a variety of shapes/colors/locations with user-defined labels

### ISSUE THREAD

**Issue by johndeverall** [johndeverall/BehaviourCoder#9]
Not all studies this tool will be used for will be mirror recognition studies. Therefore the mirror should be optional. Also the label on the mirror should be renameable, and its position able to be adjusted (so it could become a divider / screen or something else). Rather than implement this feature - heading down the SVG track or similar as in #8 might make more sense.

**Comment by johndeverall** [comment]
@alexisgarland can you please clarify this requirement

**Comment by alexisgarland** [comment]
Essentially the user needs to be able to add in static objects (can be very simple button-like shapes - square/rectangle/circle, with selectable color) - that serve as location reference points for the central buttons. The central buttons are essentially forming a map of locations that the animal(s) are spending time in - and this is often in reference to an object/area. In the rooster's case it was a mirror, in the Myna's case it was a stuffed hawk for one task and a mirror for another - sometimes it's fake trees or even another animal.

**Comment by alexisgarland** [comment]
Duplicate
